#!/usr/bin/env python3
import argparse,json
from pathlib import Path

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--map',type=Path,required=True); ap.add_argument('--output',type=Path,required=True); args=ap.parse_args(); m=json.loads(args.map.read_text()); lessons=[]
    for f in m.get('selected_fights',[]):
        fid=f['fight_id']; status=f.get('outcome','unresolved'); category=f.get('lesson_category','decision'); label={'new_best_example':'model_success','progression_checkpoint':'progression','different_version_of_exposure':'different_version','different_version_of_reset':'different_version','repeated_group_pressure':'repeated_mistake','positive_survival_progression':'progression'}.get(f.get('novelty'),'new_lesson')
        cue={'fight_04':'Bad first trade: break the line.','fight_06':'Know the container exit before the close fight.','fight_10':'Optional target: keep a roof retreat.','fight_11':'When one becomes several, shrink the angle.','fight_13':'After damage, use the doorway before the next shot.','fight_14':'A reset is a position, not just a heal.','fight_16':'Loot can wait; cover and aim cannot.','fight_19':'After a fast kill, change the lane.','fight_21':'A clean kill is permission to leave.','fight_23':'After emergency melee, move before looting.','fight_24':'A safe escape protects the extraction goal.','fight_25':'Smoke hides you; new cover keeps you alive.','fight_26':'Use height for target order, not panic shots.','fight_27':'Let footsteps set the crosshair.','fight_28':'Near extraction, finish fast and keep moving.'}.get(fid,'Protect the route before chasing the next advantage.')
        lessons.append({'lesson_id':fid+'_lesson','source_fight_id':fid,'lesson_type':'goal_tradeoff' if 'loot' in f.get('goal_relation','') or 'extraction' in f.get('goal_relation','') else 'position','novelty_label':label,'progression_note':f.get('novelty'),'goal_relation':f.get('goal_relation'),'review_depth':f.get('review_depth','standard'),'decision_point':{'source_time':f.get('decision_time',f.get('combat_start',f.get('source_start'))),'description':f.get('lesson','Decision point from the contextual coaching map.'),'evidence_refs':[fid+'.decision_time',fid+'.outcome_time']},'observed':[f.get('player_knew','Visible player knowledge and action require source review.'),f'The source shows a {status} outcome.'],'inferred':[f"At {f.get('location','this location')}, the lesson likely changes the player’s options; verify the exact geometry against the source."],'unknown':f.get('unknowns',['Enemy intent and off-screen information are not established.']),'what_helped':'The player’s response to the immediate threat is preserved as evidence, even when the outcome is unfavorable.','what_hurt':f.get('lesson','The turning point requires a source-specific explanation.'),'realistic_alternative':{'action':f"At {f.get('location','this location')}, apply the scene lesson and use the visible reset, route, target order, or timing that the source supports.",'tradeoff':'This may give up speed, loot access, or the current angle in exchange for more control.','likely_benefit':'This could preserve health, aim time, or the route toward extraction; it cannot guarantee a different result.','unknowns':f.get('unknowns',[])},'next_game_cue':cue,'drill':{'name':category.replace('_',' ').title()+' drill','trigger':'The same visible threat or decision pattern appears.','action':'Apply the specific cue at the first controllable moment.','success_condition':'Complete the cue before taking the next unnecessary exposure in three relevant fights.','scope':'Next three fights'}})
    args.output.parent.mkdir(parents=True,exist_ok=True); args.output.write_text(json.dumps({'lessons':lessons},indent=2)); print(json.dumps({'output':str(args.output),'lessons':len(lessons)},indent=2))
if __name__=='__main__': main()
